version: "3.8"

services:

  frontend:
    image: ghcr.io/thi-projekte/handwerker/frontend:latest

    container_name: frontend

    restart: unless-stopped

    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true