version: "3.8"

services:

  frontend:
    image: ghcr.io/thi-projekte/craftvoice-frontend:latest

    container_name: craftvoice-frontend

    restart: unless-stopped

    networks:
      - nginx-reverse-proxy

networks:
  nginx-proxy-manager:
    external: true