# Datenbankverbindung
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:catalog-db}

# Schema automatisch aktualisieren (nur Entwicklung)
# ?? NICHT für Produktivsysteme geeignet
quarkus.hibernate-orm.database.generation=update

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# Keycloak
quarkus.oidc.tenant-enabled=${QUARKUS_OIDC_TENANT_ENABLED:false}
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:https://id-craftvoice.winfprojekt.de}/realms/handwerker-realm
quarkus.oidc.client-id=mein-frontend
quarkus.oidc.application-type=service

# quarkus.http.auth.permission.authenticated.paths=/catalog/*
# quarkus.http.auth.permission.authenticated.policy=authenticated

# CORS Configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,https://cv.winfprojekt.de,https://craftvoice.winfprojekt.de
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type,Accept
